//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Asp.Net_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctabl
    {
        public int did { get; set; }
        public string dname { get; set; }
        public string dAddress { get; set; }
        public string dGender { get; set; }
        public int Age { get; set; }
        public long Phone_No { get; set; }
    }
}
