//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Asp.Net_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstd
    {
        public int mid { get; set; }
        public string mname { get; set; }
        public string maddress { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
    }
}
