//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_Asp.Net_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Std_table
    {
        public int Sid { get; set; }
        public string Sname { get; set; }
        public string Saddress { get; set; }
        public string Sgender { get; set; }
        public int Age { get; set; }
        public long Phone_No { get; set; }
    }
}
